import os

# CREDENTIALS
BOT_AUTH_TOKEN = os.environ['BOT_AUTH_TOKEN']
GOOGLE_API_KEY = os.environ['GOOGLE_SEARCH_API_KEY']
GOOGLE_CSE_KEY = os.environ['GOOGLE_CSE_ID']
DATABASE_URL=os.environ['DATABASE_URL']